name: Build iLoveOPUS Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: iLoveOPUSWin
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy mutagen pillow pyinstaller
      - name: Install nasm
        run: choco install nasm
      - name: Build FFMPEG
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          ./configure \
            --disable-doc \
            --disable-programs \
            --enable-static \
            --disable-shared \
            --disable-debug \
            --enable-libopus \
            --enable-libmp3lame \
            --enable-libfdk-aac \
            --enable-gpl \
            --enable-nonfree \
            --enable-pic \
            --enable-small \
            --disable-everything \
            --enable-encoder=libopus,libmp3lame,libfdk_aac \
            --enable-decoder=mp3,aac,flac,alac,opus \
            --enable-demuxer=mp3,aac,flac,alac,ogg,wav \
            --enable-muxer=opus,ogg,mp3,flac,wav \
            --enable-parser=opus,flac,aac,mp3 \
            --enable-protocol=file
          make -j2
          cd ..
      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name iLoveOPUSWin
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSWin
          path: dist/iLoveOPUSWin.exe

  build-linux:
    name: iLoveOPUSLinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential libgl1-mesa-dev
          sudo apt-get install -y autoconf automake cmake git libtool pkg-config texinfo wget yasm nasm zlib1g-dev libx264-dev libx265-dev libvpx-dev libfdk-aac-dev libmp3lame-dev
          python -m pip install --upgrade pip
          pip install kivy mutagen pillow pyinstaller
      - name: Install nasm
        run: sudo apt-get install -y nasm
      - name: Build FFMPEG
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          ./configure \
            --disable-doc \
            --disable-programs \
            --enable-static \
            --disable-shared \
            --disable-debug \
            --enable-libopus \
            --enable-libmp3lame \
            --enable-libfdk-aac \
            --enable-gpl \
            --enable-nonfree \
            --enable-pic \
            --enable-small \
            --disable-everything \
            --enable-encoder=libopus,libmp3lame,libfdk_aac \
            --enable-decoder=mp3,aac,flac,alac,opus \
            --enable-demuxer=mp3,aac,flac,alac,ogg,wav \
            --enable-muxer=opus,ogg,mp3,flac,wav \
            --enable-parser=opus,flac,aac,mp3 \
            --enable-protocol=file
          make -j2
          cd ..
      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name iLoveOPUSLinux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSLinux
          path: dist/iLoveOPUSLinux

  build-macos:
    name: iLoveOPUSMac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          brew install python3
          python3 -m pip install --upgrade pip
          pip3 install kivy mutagen pillow pyinstaller
      - name: Build FFMPEG
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          ./configure \
            --disable-doc \
            --disable-programs \
            --enable-static \
            --disable-shared \
            --disable-debug \
            --enable-libopus \
            --enable-libmp3lame \
            --enable-libfdk-aac \
            --enable-gpl \
            --enable-nonfree \
            --enable-pic \
            --enable-small \
            --disable-everything \
            --enable-encoder=libopus,libmp3lame,libfdk_aac \
            --enable-decoder=mp3,aac,flac,alac,opus \
            --enable-demuxer=mp3,aac,flac,alac,ogg,wav \
            --enable-muxer=opus,ogg,mp3,flac,wav \
            --enable-parser=opus,flac,aac,mp3 \
            --enable-protocol=file
          make -j2
          cd ..
      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name iLoveOPUSMac
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSMac
          path: dist/iLoveOPUSMac