name: Build iLoveOPUS Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: iLoveOPUSLinux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev build-essential libgl1-mesa-dev
          python -m pip install --upgrade pip
          pip install kivy mutagen pillow pyinstaller
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
      - name: Build executable
        run: |
          KIVY_DATA_PATH=$(python3 -c 'import kivy; import os; print(os.path.join(os.path.dirname(kivy.__file__), "data"))')
          pyinstaller --onefile main.py --name iLoveOPUSLinux --add-data "style.kv:." --add-data "$KIVY_DATA_PATH:kivy_data"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSLinux
          path: dist/iLoveOPUSLinux