name: Build iLoveOPUS Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: iLoveOPUSMac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          brew install python3 ffmpeg
          python3 -m pip install --upgrade pip
          pip3 install kivy mutagen pillow pyinstaller
      - name: Build executable
        run: |
          KIVY_DATA_PATH=$(python3 -c 'import kivy; import os; print(os.path.join(os.path.dirname(kivy.__file__), "data"))')
          pyinstaller --onefile main.py --name iLoveOPUSMac --add-data "style.kv:." --add-data "$KIVY_DATA_PATH:kivy/data"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSMac
          path: dist/iLoveOPUSMac
