name: Build iLoveOPUS Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: iLoveOPUSWin
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy mutagen pillow pyinstaller
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
      - name: Build executable
        shell: cmd
        run: |
          set KIVY_GL_BACKEND=angle_sdl2
          set KIVY_METRICS_DENSITY=1
          set KIVY_NO_ARGS=1
          set KIVY_NO_CONSOLELOG=1
          for /f "delims=" %%K in ('python -c "import kivy, os; print(os.path.join(os.path.dirname(kivy.__file__), 'data'))"') do set KIVY_DATA_PATH=%%K
          pyinstaller --onefile main.py --name iLoveOPUSWin --add-data "style.kv;." --add-data "%KIVY_DATA_PATH%;kivy/data"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSWin
          path: dist/iLoveOPUSWin.exe
