name: Build iLoveOPUS Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: iLoveOPUSWin
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy mutagen pillow pyinstaller
      - name: Download FFmpeg binary
        run: |
          curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2025-06-13-13-43/ffmpeg-n7.1.1-22-g0f1fe3d153-winarm64-gpl-7.1.zip
          unzip ffmpeg.zip -d ffmpeg_bin
      - name: Add FFmpeg to PATH
        run: |
          echo "${{ github.workspace }}/ffmpeg_bin/ffmpeg-n7.1.1-22-g0f1fe3d153-winarm64-gpl-7.1/bin" >> $GITHUB_PATH
      - name: Build executable
        shell: cmd
        run: |
          set KIVY_GL_BACKEND=angle_sdl2
          set KIVY_METRICS_DENSITY=1
          set KIVY_NO_ARGS=1
          set KIVY_NO_CONSOLELOG=1
          pyinstaller --onefile main.py --name iLoveOPUSWin --add-data "style.kv;."
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iLoveOPUSWin
          path: dist/iLoveOPUSWin.exe
